/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Gezimi' at '11/9/16 11:06 PM' with Gradle 2.13
 *
 * @author Gezimi, @date 11/9/16 11:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
